 node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://git.cgi.com/palash.moon/emailValidation.git', credentialsId: '', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('EurekaServers') {
                def app = docker.build "localhost:50000/discovery-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:50000/discovery-service:${env.version}").run('-p 8761:8761 -h discovery-service --name discovery-service')
        }

        stage ('Final') {
            build job: 'config-server-pipeline', wait: false
        }      

    }

}